# using build procedure from: https://github.com/PHPirates/travis-ci-latex-pdf/blob/master/4-texlive

language: generic
dist: bionic

install:
  - source ./texlive/texlive_install.sh
  - pip install ghp-import --user

cache:
  directories:
    - /tmp/texlive
    - $HOME/.texlive

script:
 - cd whitepaper
 - make latex

deploy:
  - provider: releases
    skip_cleanup: true
    file: ../_build/main.pdf
    api_key: $GITHUB_TOKEN
    on:
      tags: true
  - provider: script
    skip_cleanup: true
    script: make github
    on:
      branch: master
